### 生成数据集 

In [1]:
import numpy
import tensorflow as tf

In [2]:
def synthetic_data(w, b, num_examples):  #@save
    """生成y=Xw+b+噪声"""
    X = tf.zeros((num_examples, w.shape[0]))
    X += tf.random.normal(shape=X.shape)
    y = tf.matmul(X, tf.reshape(w, (-1, 1))) + b
    y += tf.random.normal(shape=y.shape, stddev=0.01)
    y = tf.reshape(y, (-1, 1))
    return X, y

In [3]:
true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)

### 读取数据集 

In [7]:
def load_array(data_arrays, batch_size, is_train=True):
    '''
    Parameters\n
    - is_train : 是否在每个迭代周期内打乱顺序 
    '''
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays) # 用来把每个样本的feature和label
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size) # 划分batch
    return dataset


In [5]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [6]:
for data in data_iter:
    print(data)
    break

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[-0.611035  ,  0.114004  ],
       [-0.45226982,  1.3199145 ],
       [-1.6873332 , -0.5913188 ],
       [ 1.2383558 , -0.02191277],
       [ 1.800311  ,  1.2321577 ],
       [-0.9123915 , -0.27701122],
       [-0.15132841,  0.5264662 ],
       [-0.23542288, -0.7864649 ],
       [-0.3037398 , -0.5067806 ],
       [ 0.56812906, -0.6825509 ]], dtype=float32)>, <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 2.596919 ],
       [-1.1839564],
       [ 2.821555 ],
       [ 6.7503448],
       [ 3.620641 ],
       [ 3.336409 ],
       [ 2.1190257],
       [ 6.4106236],
       [ 5.309436 ],
       [ 7.649465 ]], dtype=float32)>)
